### ISSUE TITLE
ctrl-tab no longer switches conversation tabs

### ISSUE THREAD

**Issue by lxcode** [dm0-/window_merge#11]
After installing and enabling the window_merge plugin, switching conversations with ctrl-tab is no longer functional.

This is using Pidgin 2.10.6 and window_merge 0.3. Thanks for the plugin!

**Comment by dm0-** [comment]
Thanks for reporting.  I have pushed a change that seems to correct the issue for me.  I have also updated the prebuilt Windows plugin on the downloads page, if you need it.  Let me know if the issue persists.
