### ISSUE TITLE
fatal error: gtkblist.h: No such file or directory

### ISSUE THREAD

**Issue by sinanerdem** [dm0-/window_merge#16]
When I execute the last step of build: make distcheck, I receive following errors:

make[1]: Entering directory `/usr/share/window_merge/window_merge-0.3/_build'
make  all-am
make[2]: Entering directory`/usr/share/window_merge/window_merge-0.3/_build'
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT window_merge_la-dummy.lo -MD -MP -MF .deps/window_merge_la-dummy.Tpo -c -o window_merge_la-dummy.lo `test -f 'dummy.c' || echo '../'`dummy.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -g -O2 -MT window_merge_la-dummy.lo -MD -MP -MF .deps/window_merge_la-dummy.Tpo -c ../dummy.c  -fPIC -DPIC -o .libs/window_merge_la-dummy.o
../dummy.c:31:22: fatal error: gtkblist.h: No such file or directory
compilation terminated.
make[2]: **\* [window_merge_la-dummy.lo] Error 1
make[2]: Leaving directory `/usr/share/window_merge/window_merge-0.3/_build'
make[1]: *** [all] Error 2
make[1]: Leaving directory`/usr/share/window_merge/window_merge-0.3/_build'
make: **\* [distcheck] Error 1

**Comment by dm0-** [comment]
The file gtkblist.h is provided by the Pidgin source.  Do you see a warning line in the configure output that says Pidgin was not found?

If you are using a GNU/Linux distribution's package manager, verify that a package named "pidgin-dev" or "pidgin-devel" is installed.  Pre-built development packages like this should provide a pkg-config file to automatically tell the plugin's configure script where to find Pidgin headers.

If you know you have Pidgin headers installed properly and it still doesn't work, try running something like the following before your "make" command to see if it finds the headers:

```
export pidgin_CFLAGS=-I/usr/include/pidgin pidgin_LIBS=-lpidgin
```

**Comment by dm0-** [comment]
I will close this ticket, as I believe this was an issue with the Pidgin installation rather than this plugin.  Feel free to reopen it if this does not appear to be the case.

**Comment by reedstrm** [comment]
For future finders of this issue - make sure you have pidigin-dev installed, and _then_ run the ./configure step.

**Comment by jaggzh** [comment]
How's about in the list of dependencies in the readme, include "*Possibly pidgin-dev on some platforms" (or something)?
