### ISSUE TITLE
‘G_VALUE_INIT’ undeclared

### ISSUE THREAD

**Issue by mayasd** [dm0-/window_merge#17]
Hi,
Logs : http://pastebin.com/70Grvk6f
pidgin : 2.7.3-1+squeeze3
pidgin-dev : 2.7.3-1+squeeze3
window-merge : 0.3

For fixing this, i add :
# define G_VALUE_INIT {0,{{0}}}

In files merge.c et utils.c
Make works fine after.

**Comment by dm0-** [comment]
Thanks for the report.  I've updated the configure script in 76dcbbb6 to supply a compatibility definition when glib is older than [version 2.30](https://developer.gnome.org/gobject/stable/api-index-2-30.html).
