### ISSUE TITLE
Windows dlll

### ISSUE THREAD

**Issue by CP1832** [dm0-/window_merge#19]
I'm not reporting an issue, just letting available Window merge dll for Windows: https://sites.google.com/site/dm0uploads/window_merge.dll

**Comment by BWMerlin** [comment]
Am I missing something?  The linked .dll file is older than the one available on the main page.

**Comment by ghost** [comment]
get your 0.3 DLL here:
https://dl.dropboxusercontent.com/u/7590064/window_merge.dll

**Comment by dm0-** [comment]
A few months ago, GitHub decided they wanted to remove downloads for everybody.  The hosted files are still available at their original URLs, but all links have been hidden and no new files can be uploaded.  (There is an admittedly missable explicit download link in this project's README.md.)  You can still get the Windows binaries at https://github.com/dm0-/window_merge/downloads/ .

I have put the files on an independent host as well, to avoid any potential GitHub / Google shenanigans in the future:  http://dm0.me/projects/window_merge
