### ISSUE TITLE
Failed to build, please provide some releases

### ISSUE THREAD

**Issue by opi** [dm0-/window_merge#25]
Hi,

Running 'Ubuntu 14.04.3 LTS', I failed to build your plugin. 

First I have to understand that I need pidgin-dev package, please indicate this on your readme (maybe I'll provide a PR)

Then, when running the `make distcheck` I ran on several issues about missing C header files. I have to install libgtk-3-dev, ...
Errors were like "gtk/gtk.h: No such file or directory", "gdk/gdk.h: No such file or directory", "fatal error: gio/gio.h: No such file or directory"

I really like to have your plugin installed, but if I have to become a C programmer, I'll give up.

**Comment by dm0-** [comment]
Releases have been uploaded here: https://github.com/dm0-/window_merge/downloads

There are two READMEs in the project, one in plain text for releases and one in markdown for the GitHub project page.  The plain text README does say that pidgin-dev provides the development files, and README.md (on the main project page) links to the Wiki where instructions for Ubuntu were contributed.

Also, you don't need GTK+ 3.  Installing Pidgin development files should have pulled in the GTK+ 2 development files, which provides the headers it wants.
