### ISSUE TITLE
change your buddyicon always left

### ISSUE THREAD

**Issue by hasufell** [dm0-/window_merge#3]
When I set Conversation Pane Left of Buddy List the "change your buddyicon" icon is still on the left side.

This does not happen with "above" and "below".

**Comment by dm0-** [comment]
This is actually a bug in Pidgin.  I submitted the fix to them, but there hasn't been any action on it as of yet.  Here is the ticket on their tracker if you want to upvote it: http://developer.pidgin.im/ticket/15046 .  (You could also just rebuild Pidgin with the patch to fix it locally).  I'll leave your ticket open here until it is fixed, so others can see it is a known issue.

**Comment by hasufell** [comment]
confirmed

I applied your patch and the issue is gone.

**Comment by dm0-** [comment]
Pidgin 2.10.7 has been released which contains this fix, among other crash/freeze fixes for the plugin.  I will close this ticket, since the issue should now be resolved when Pidgin is up to date.
