### ISSUE TITLE
segfault conflict when window_merge and infopane plugin activated at the same time

### ISSUE THREAD

**Issue by mrueg** [dm0-/window_merge#4]
gdb backtrace: http://dpaste.com/732265/

pidgin: 2.10.3
window_merge: d8a8ce335f01f6b60de9302c74d33fed2f1ba5b2
purple-plugin_pack: 2.7.0

Steps to reproduce:
- Activate window_merge and infopane plugin
- Open conversation windows > 2
- Last conversation window closed = segfault

**Comment by dm0-** [comment]
Thanks for reporting.  I checked out Infopane's source, and there doesn't look like anything I can do with the current structure of this plugin.  Infopane assumes that each PidginConversation has a valid PurpleConversation underneath it, but this plugin's dummy conversation (for receiving dragged conversations into the Buddy List, etc.) is only an interface with no real conversation under it.  This results in NULL pointer dereferences.

I can submit a patch against infopane.c to do some NULL checks a bit later, but I don't see anything to change in this plugin (short of redesigning it).  I will update this ticket when I get a chance to send a fix upstream.

**Comment by dm0-** [comment]
I have briefly tested and submitted a patch to infopane.c here: https://www.guifications.org/issues/716 .
