### ISSUE TITLE
Conversation menu items are lost

### ISSUE THREAD

**Issue by thesame** [dm0-/window_merge#7]
In my installation of Piding Conversation winodw has "Conversation", "Options", "Send To" and "<encrypt>" main menu items. After installing window_merge these items are merged with contact-list main menu, and "Senf To" and "<encrypt>" items are disappeared.

What expected: all menu items are visible.

**Comment by dm0-** [comment]
Thanks for the report.

I'm not sure what you mean with a "" menu item.  Do you get an actual submenu from a blank label?  I see the conversation window menu bar has a blank item that was apparently once used for a typing icon.  It seems to only be referenced in an "#if 0" block, so I think it can safely be ignored.

The "Send To" item is more complicated.  I'd prefer to call it a Pidgin bug.  If you are able to rebuild Pidgin, you can apply the patch attached to the following ticket to fix the issue.

http://developer.pidgin.im/ticket/15233

I'd like to give them a little while to consider fixing it in Pidgin.  (Hopefully it will at least get a response.)  If nothing happens with it, I can try to figure out some workaround for it in the plugin.

**Comment by thesame** [comment]
a "" menu item is a menu item with an encryption icon created by Pidgin-Encryption plugin. Github parser ate my string in angle brackets.

**Comment by dm0-** [comment]
I've pushed a change that should handle menu items in a more general, less conflict-y way.  It seems to work with Pidgin Encryption for me.  It does not yet attempt handle the "Send To" menu.

Note that if you enable Pidgin Encryption after you have conversations open in the Buddy List window, you will have to close them all before it will pick up the new menu item.  When the "Send To" menu is fixed, I should be able to have new items added to the Buddy List menu bar immediately.

I'll leave this ticket open while it depends on a Pidgin ticket.
