### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by breunigs** [dm0-/window_merge#8]
I’m not sure how to build window_merge because either the code on GitHub is incomplete or the readme is misleading. It states to run ./configure, yet this file is not included. Neither is the INSTALL file where it is mentioned I found find more verbose instructions. I tried running automake, but it exits with an error. 

Can you give me any hints? Thanks.

**Comment by dm0-** [comment]
Yes, sorry about the README file being misleading.  It was intended for use with the distribution tars (available on the downloads page) where configure etc. are included.  My intent was to keep all of the automatically generated files out of git.  I suppose it may be worth adding a README.md for GitHub-specific information.

Instructions can be found on the main wiki page for various building scenarios.  I think you want the following section:

```
git clone https://github.com/dm0-/window_merge.git
cd window_merge
mkdir m4
autoreconf -fi
```

This should get your configure script created.  Let me know if there are problems with this.

**Comment by breunigs** [comment]
this worked, thanks!
